# Generated by Django 4.2.11 on 2024-10-24 10:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('show_products', '0013_categories_image_url'),
        ('rating', '0002_remove_productrating_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productrating',
            old_name='description',
            new_name='comment',
        ),
        migrations.AddField(
            model_name='productrating',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='show_products.product'),
        ),
        migrations.AlterField(
            model_name='productrating',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productrating',
            name='rating',
            field=models.PositiveIntegerField(),
        ),
    ]
