# Generated by Django 4.2.11 on 2024-10-24 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('show_products', '0013_categories_image_url'),
        ('rating', '0003_rename_description_productrating_comment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productrating',
            old_name='comment',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='productrating',
            name='created_at',
        ),
        migrations.AddField(
            model_name='productrating',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productrating',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show_products.product'),
        ),
        migrations.AlterField(
            model_name='productrating',
            name='rating',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
