# Generated by Django 4.2.11 on 2024-10-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0004_rename_comment_productrating_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productrating',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productrating',
            name='user',
        ),
        migrations.AlterField(
            model_name='productrating',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
