# Generated by Django 4.2.11 on 2024-10-24 12:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0005_remove_productrating_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrating',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
