# Generated by Django 4.2.11 on 2024-10-24 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0009_alter_productrating_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productrating',
            name='created_at',
        ),
    ]
