# Generated by Django 5.1.1 on 2024-10-22 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
                ('unique_products', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(upload_to='')),
                ('product_name', models.CharField(max_length=255)),
                ('product_subtitle', models.CharField(max_length=255)),
                ('sold_this_week', models.IntegerField()),
                ('people_bought', models.IntegerField()),
                ('product_description', models.TextField()),
                ('product_advantages', models.TextField()),
                ('product_material', models.CharField(max_length=255)),
                ('product_length', models.IntegerField()),
                ('product_height', models.IntegerField()),
                ('product_long', models.IntegerField()),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show_products.categories')),
            ],
        ),
    ]
