# Generated by Django 5.1.1 on 2024-10-22 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show_products', '0002_alter_categories_id_alter_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_height',
            new_name='product_size_height',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_length',
            new_name='product_size_length',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_long',
            new_name='product_size_long',
        ),
    ]
