# Generated by Django 5.1.1 on 2024-10-22 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show_products', '0003_rename_product_height_product_product_size_height_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='unique_products',
        ),
    ]
