# Generated by Django 5.1.1 on 2024-10-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_products', '0005_alter_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='produt_price',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='people_bought',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_size_height',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_size_length',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_size_long',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='sold_this_week',
            field=models.PositiveIntegerField(),
        ),
    ]
