# Generated by Django 5.1.1 on 2024-10-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_products', '0006_product_produt_price_alter_product_people_bought_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_price',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
