# Generated by Django 5.1.1 on 2024-10-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_products', '0008_remove_product_produt_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='unique_products',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
