# Generated by Django 5.1.1 on 2024-10-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_products', '0011_alter_product_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='unique_products',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
