# Generated by Django 5.1.2 on 2024-12-19 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_products', '0014_product_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='store_address',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='store_name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_rating',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
