# Generated by Django 4.2.11 on 2024-12-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_products', '0014_product_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='store_address',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='store_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_rating',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
