# Generated by Django 5.1.2 on 2024-10-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', max_length=10),
        ),
    ]
