# Generated by Django 5.1.1 on 2024-10-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tipe',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
