# Generated by Django 5.1.2 on 2024-10-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=10),
        ),
    ]
