# Generated by Django 5.1.2 on 2024-10-26 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editp', '0002_userprofile_role'),
        ('editp', '0003_alter_userprofile_tipe'),
    ]

    operations = [
    ]
