# Generated by Django 5.1.1 on 2024-10-26 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editp', '0004_alter_userprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
